const String catFolder = 'assets/images/product_category';
const String prodFolder = 'assets/images/product_category';

const List<Map> category = [
  {
    'c': 'Buah dan Sayur Organik',
    't': ['buah', 'sayur', 'organik'],
    'p': '$catFolder/sayur.png',
  },
  {
    'c': 'Daging dan Ikan Organik',
    't': ['daging', 'ikan', 'organik'],
    'p': '$catFolder/daging.png',
  },
  {
    'c': 'Produk Olahan Organik',
    't': ['produk', 'olahan', 'organik'],
    'p': '$catFolder/produk.png',
  },
  {
    'c': 'Pupuk Kompos',
    't': ['pupuk', 'kompos'],
    'p': '$catFolder/pupuk.png',
  },
];

const List<Map> products = [
  {
    'idCategory': 0,
    'name': 'Sawi Organik',
    'img': '$prodFolder/sayur.png',
    'owner': 'Cikgu',
    'lower': ['sawi', 'organik'],
    'price': 15000,
    'unit': 'ikat',
    'rating': 5,
    'sold': 50,
    'stock': 10,
  },
  {
    'idCategory': 0,
    'name': 'Sawi Putih Organik',
    'img': '$prodFolder/sayur.png',
    'owner': 'Sayur Segar',
    'lower': ['sawi', 'putih', 'organik'],
    'price': 16000,
    'unit': 'pc',
    'rating': 4,
    'sold': 45,
    'stock': 10,
  },
  {
    'idCategory': 0,
    'name': 'Sawi Organik',
    'img': '$prodFolder/sayur.png',
    'owner': 'Kang Bayu',
    'lower': ['sawi', 'organik'],
    'price': 18000,
    'unit': 'bungkus',
    'rating': 3,
    'sold': 55,
    'stock': 10,
  },
  {
    'idCategory': 0,
    'name': 'Sawi Putih Organik',
    'img': '$prodFolder/sayur.png',
    'owner': 'Raden',
    'lower': ['sawi', 'putih', 'organik'],
    'price': 15000,
    'unit': 'pc',
    'rating': 2,
    'sold': 20,
    'stock': 10,
  },
  {
    'idCategory': 1,
    'name': 'Hiu Segar',
    'img': '$prodFolder/daging.png',
    'owner': 'Bambang',
    'lower': ['hiu', 'segar'],
    'price': 36000,
    'unit': 'ekor',
    'rating': 1,
    'sold': 45,
    'stock': 10,
  },
  {
    'idCategory': 2,
    'name': 'Salad Buah',
    'img': '$prodFolder/produk.png',
    'owner': 'Yummy',
    'lower': ['salad', 'buah'],
    'price': 15000,
    'unit': 'pc',
    'rating': 5,
    'sold': 35,
    'stock': 10,
  },
  {
    'idCategory': 3,
    'name': 'Pupuk N35',
    'img': '$prodFolder/pupuk.png',
    'owner': 'Makrobos',
    'lower': ['pupuk', 'n35'],
    'price': 30000,
    'unit': 'karung',
    'rating': 4,
    'sold': 20,
    'stock': 10,
  },
];
