const List<Map> category = [
  {
    'c': 'Buah dan Sayur Organik',
    't': ['buah', 'sayur', 'organik'],
    'p': '',
  },
  {
    'c': 'Daging dan Ikan Organik',
    't': ['daging', 'ikan', 'organik'],
    'p': '',
  },
  {
    'c': 'Produk Olahan Organik',
    't': ['produk', 'olahan', 'organik'],
    'p': '',
  },
  {
    'c': 'Pupuk Kompos',
    't': ['pupuk', 'kompos'],
    'p': '',
  },
];

const List<Map> products = [
  {
    'idCategory': 0,
    'name': 'Sawi Organik',
    'img': '',
    'owner': 'Cikgu',
    'lower': ['sawi', 'organik'],
    'price': 15000,
    'unit': 'ikat',
    'point': 15,
    'rating': 5,
    'sold': 50,
  },
  {
    'idCategory': 0,
    'name': 'Sawi Putih Organik',
    'img': '',
    'owner': 'Sayur Segar',
    'lower': ['sawi', 'putih', 'organik'],
    'price': 16000,
    'unit': 'pc',
    'point': 16,
    'rating': 5,
    'sold': 45,
  },
  {
    'idCategory': 0,
    'name': 'Sawi Organik',
    'img': '',
    'owner': 'Kang Bayu',
    'lower': ['sawi', 'organik'],
    'price': 18000,
    'unit': 'bungkus',
    'point': 18,
    'rating': 5,
    'sold': 55,
  },
  {
    'idCategory': 0,
    'name': 'Sawi Putih Organik',
    'img': '',
    'owner': 'Raden',
    'lower': ['sawi', 'putih', 'organik'],
    'price': 15000,
    'unit': 'pc',
    'point': 15,
    'rating': 5,
    'sold': 20,
  },
  {
    'idCategory': 1,
    'name': 'Hiu Segar',
    'img': '',
    'owner': 'Bambang',
    'lower': ['hiu', 'segar'],
    'price': 36000,
    'unit': 'ekor',
    'point': 40,
    'rating': 5,
    'sold': 45,
  },
  {
    'idCategory': 2,
    'name': 'Salad Buah',
    'img': '',
    'owner': 'Yummy',
    'lower': ['salad', 'buah'],
    'price': 15000,
    'unit': 'pc',
    'point': 15,
    'rating': 5,
    'sold': 35,
  },
  {
    'idCategory': 3,
    'name': 'Pupuk N35',
    'img': '',
    'owner': 'Makrobos',
    'lower': ['pupuk', 'n35'],
    'price': 30000,
    'unit': 'karung',
    'point': 30,
    'rating': 4,
    'sold': 20,
  },
];
